add_executable (Delete delete.cpp)
add_executable (Set set.cpp)
add_executable (Map map.cpp)
add_executable (StableSet stable_set.cpp)

target_link_libraries(Set       PRIVATE ptrie doctest::doctest_with_main)
target_link_libraries(Delete    PRIVATE ptrie doctest::doctest_with_main)
target_link_libraries(StableSet PRIVATE ptrie doctest::doctest_with_main)
target_link_libraries(Map       PRIVATE ptrie doctest::doctest_with_main)

add_test(NAME Set       COMMAND Set)
add_test(NAME Delete    COMMAND Delete)
add_test(NAME StableSet COMMAND StableSet)
add_test(NAME Map       COMMAND Map)

# Adds heaptrack tests for given tests (reuses their COMMAND property)
macro(add_heaptrack_for_tests)
    message(STATUS "add_heaptrack_for_tests(${ARGN})")
    if (HEAPTRACK)
        set(_names ${ARGN})
        foreach(_name IN LISTS _names)
            get_property(_command TEST ${_name} PROPERTY COMMAND)
            message(STATUS "test=${_name} command=${_command}")
            add_heaptrack(NAME ${_name} COMMAND ${_command})
        endforeach()
    endif (HEAPTRACK)
endmacro()

if (NOT ASAN AND NOT LSAN)
    add_heaptrack_for_tests(Set Delete StableSet Map)
endif()
