find_program(HEAPTRACK NAMES heaptrack)
if (HEAPTRACK)
    if (ASAN OR LSAN)
        message(STATUS "Disabled heaptrack (incompatible with sanitizers")
        set(HEAPTRACK OFF)
    else ()
        find_program(HEAPTRACK_PRINT NAMES heaptrack_print)
        if (HEAPTRACK_PRINT)
            message(STATUS "Found heaptrack and heaptrack_print, enabling heap tracking tests")
        else (HEAPTRACK_PRINT)
            message(STATUS "Failed to find heaptrack_print, heap tracking is going to be disabled")
            set(HEAPTRACK OFF)
        endif (HEAPTRACK_PRINT)
    endif ()
else (HEAPTRACK)
    message(STATUS "Failed to find heaptrack, heap tracking is going to be disabled")
endif (HEAPTRACK)

# Adds heaptracking test with arguments just like add_test
macro(add_heaptrack)
    if (HEAPTRACK)
        #message(STATUS "add_heaptrack(${ARGN}")
        cmake_parse_arguments(ARG "COMMAND_EXPAND_LISTS" "NAME;WORKING_DIRECTORY" "COMMAND;CONFIGURATIONS" ${ARGN})
        if (NOT ARG_NAME)
            message(FATAL_ERROR "NAME is required")
        endif()
        if (NOT ARG_COMMAND)
            message(FATAL_ERROR "COMMAND is required")
        endif()
        # Split command from its arguments
        set(_arg_list ${ARG_COMMAND})
        list(POP_FRONT _arg_list _command)
        # Resolve target to executable if needed (e.g. `Ninja Multi-Config` has extra folder in the path)
        if (TARGET ${_command})
            set(_command $<TARGET_FILE:${_command}>)
        endif()
        set(_optional)
        if (ARG_CONFIGURATIONS)
            list(APPEND _optional CONFIGURATIONS ${ARG_CONFIGURATIONS})
        endif()
        if (ARG_WORKING_DIRECTORY)
            list(APPEND _optional WORKING_DIRECTORY ${ARG_WORKING_DIRECTORY})
        endif()
        if (ARG_COMMAND_EXPAND_LISTS)
            list(APPEND _optional COMMAND_EXPAND_LISTS)
        endif()
        add_test(NAME ${ARG_NAME} COMMAND ${HEAPTRACK} --record-only -o ${ARG_NAME} ${_command} ${_arg_list} ${_optional})
        #message(STATUS "   ${HEAPTRACK} --record-only -o ${ARG_NAME} ${_command} ${_arg_list}")
        if (HEAPTRACK_PRINT)
            add_test(NAME ${ARG_NAME}_heap COMMAND
                ${HEAPTRACK_PRINT} --print-peaks=0 --print-allocators=0 --print-temporary=0 --print-leaks=1 --suppressions ${PROJECT_SOURCE_DIR}/cmake/heaptrack_suppress.txt ${ARG_NAME}.zst ${_optional})
            set_tests_properties(${ARG_NAME}_heap PROPERTIES DEPENDS ${ARG_NAME}
                PASS_REGULAR_EXPRESSION "total memory leaked: 0B")
        endif (HEAPTRACK_PRINT)
    endif (HEAPTRACK)
endmacro()

# Adds heaptracking test if heaptracking is available, otherwise falls back to simple add_test
macro(add_heaptrack_test)
    #message(STATUS "add_heaptrack_test(${ARGN})")
    cmake_parse_arguments(ARG "COMMAND_EXPAND_LISTS" "NAME;WORKING_DIRECTORY" "COMMAND;CONFIGURATIONS" ${ARGN})
    if (NOT ARG_NAME)
        message(FATAL_ERROR "NAME is required")
    endif()
    if (NOT ARG_COMMAND)
        message(FATAL_ERROR "COMMAND is required")
    endif()
    set(_optional)
    if (ARG_CONFIGURATIONS)
        list(APPEND _optional CONFIGURATIONS ${ARG_CONFIGURATIONS})
    endif()
    if (ARG_WORKING_DIRECTORY)
        list(APPEND _optional WORKING_DIRECTORY ${ARG_WORKING_DIRECTORY})
    endif()
    if (ARG_COMMAND_EXPAND_LISTS)
        list(APPEND _optional COMMAND_EXPAND_LISTS)
    endif()
    if (HEAPTRACK)
        add_heaptrack(NAME ${ARG_NAME} COMMAND ${ARG_COMMAND} ${_optional})
    else()
        add_test(NAME ${ARG_NAME} COMMAND ${ARG_COMMAND} ${_optional})
    endif (HEAPTRACK)
endmacro()
