find_program(HEAPTRACK NAMES heaptrack)
if (HEAPTRACK)
    find_program(HEAPTRACK_PRINT NAMES heaptrack_print)
    if (HEAPTRACK_PRINT)
        message(STATUS "Found heaptrack and heaptrack_print, enabling heap tracking tests")
    else (HEAPTRACK_PRINT)
        message(STATUS "Failed to find heaptrack_print, heap tracking is going to be disabled")
        set(HEAPTRACK OFF)
    endif (HEAPTRACK_PRINT)
else (HEAPTRACK)
    message(STATUS "Failed to find heaptrack, heap tracking is going to be disabled")
endif (HEAPTRACK)

macro(add_heaptrack)
    cmake_parse_arguments(ARG "" "NAME" "COMMAND" ${ARGN})
    #message(STATUS "add_heaptrack(${TARGET_HT} ${ARGN})")
    if (HEAPTRACK)
        add_test(NAME ${ARG_NAME}_ht COMMAND ${HEAPTRACK} --record-only -o ${ARG_NAME}.ht ${ARG_COMMAND})
        if (HEAPTRACK_PRINT)
            add_test(NAME ${ARG_NAME}_leaks COMMAND
                ${HEAPTRACK_PRINT} --print-peaks=0 --print-allocators=0 --print-temporary=0 --print-leaks=1 --suppressions ${PROJECT_SOURCE_DIR}/cmake/heaptrack_suppress.txt ${ARG_NAME}.ht.zst)
            set_tests_properties(${ARG_NAME}_leaks PROPERTIES DEPENDS ${ARG_NAME}_ht COST 50
                PASS_REGULAR_EXPRESSION "total memory leaked: 0B")
        endif (HEAPTRACK_PRINT)
    endif (HEAPTRACK)
endmacro()
