---
name: Build for Windows-MSYS2-UCRT64
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - src/**
      - test/**
      - benchmark/**
      - cmake/**
      - CMakeLists.txt
      - CMakePresets.json
      - .github/workflows/build-win-msys2-ucrt64.yml
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - src/**
      - test/**
      - benchmark/**
      - cmake/**
      - CMakeLists.txt
      - CMakePresets.json
      - .github/workflows/build-win-msys2-ucrt64.yml

jobs:
  windows-msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      CMAKE_GENERATOR: "Ninja Multi-Config"
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-git mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-ninja mingw-w64-ucrt-x86_64-toolchain mingw-w64-ucrt-x86_64-sparsehash
      - name: Setup Runner Environment
        run: |
          uname -a
          CORES=$(nproc)
          echo "CMAKE_BUILD_PARALLEL_LEVEL=$CORES" >> $GITHUB_ENV
          echo "CTEST_TEST_PARALLEL_LEVEL=$CORES" >> $GITHUB_ENV
          echo "CTEST_TEST_LOAD=$CORES" >> $GITHUB_ENV
      - uses: actions/checkout@v5
      - name: Configure Multi-Config (without Sanitizers)
        run: cmake --preset multi -DBENCHMARK_PLOTS=OFF
      - name: Build Debug (without Sanitizers)
        run: cmake --build --preset debug
      - name: Test Debug (without Sanitizers)
        run: ctest --preset debug
#      - name: Build Release (without Sanitizers)
#        run: cmake --build --preset release
#      - name: Test Release (without Sanitizers)
#        run: ctest --preset release
      - name: Quick Release
        run: cmake --workflow --preset quick-release
      - name: Quick Release Install to local
        run: cmake --install build-quick --config Release --prefix "$PWD/local"
      - name: Configure Example with local
        run: cmake -S example -B build-example-local -DCMAKE_PREFIX_PATH="$PWD/local"
      - name: Build Example with local
        run: cmake --build build-example-local --config Debug
      - name: Test Example with local
        run: ctest --test-dir build-example-local -C Debug --verbose
      - name: Configure Example
        run: cmake -S example -B build-example
      - name: Build Example
        run: cmake --build build-example --config Debug
      - name: Test Example
        run: ctest --test-dir build-example -C Debug --verbose
