---
name: Build for Ubuntu-24.04
on:
  push:
    branches: [main]
    paths:
      - src/**
      - test/**
      - benchmark/**
      - cmake/**
      - CMakeLists.txt
      - CMakePresets.json
      - .github/workflows/build-ubuntu-2404.yml
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - src/**
      - test/**
      - benchmark/**
      - cmake/**
      - CMakeLists.txt
      - CMakePresets.json
      - .github/workflows/build-ubuntu-2404.yml
  workflow_dispatch:

jobs:
  ubuntu-2404:
    runs-on: ubuntu-24.04
    env:
      CMAKE_GENERATOR: "Ninja Multi-Config"
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - name: Install Build Tools
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install cmake ninja-build g++ libsparsehash-dev
      - name: Setup Runner Environment
        run: |
          uname -a
          lsb_release -a
          CORES=$(nproc)
          echo "CMAKE_BUILD_PARALLEL_LEVEL=$CORES" >> $GITHUB_ENV
          echo "CTEST_TEST_PARALLEL_LEVEL=$CORES" >> $GITHUB_ENV
          echo "CTEST_TEST_LOAD=$CORES" >> $GITHUB_ENV
      - uses: actions/checkout@v5
      - name: Configure Multi-Config with Sanitizers
        run: cmake --preset multi-san -DBENCHMARK_PLOTS=OFF
      - name: Build Debug with Sanitizers
        run: cmake --build --preset debug-san
      - name: Test Debug with Sanitizers
        run: ctest --preset debug-san
      - name: Build Release with Sanitizers
        run: cmake --build --preset release-san
      - name: Test Release with Sanitizers
        run: ctest --preset release-san
      - name: Quick Release
        run: cmake --workflow --preset quick-release
      - name: Quick Release Install to local
        run: cmake --install build-quick --config Release --prefix "$PWD/local"
      - name: Configure Example with local
        run: cmake -S example -B build-example-local -DCMAKE_PREFIX_PATH="$PWD/local"
      - name: Build Example with local
        run: cmake --build build-example-local --config Debug
      - name: Test Example with local
        run: ctest --test-dir build-example-local -C Debug --verbose
      - name: Configure Example
        run: cmake -S example -B build-example
      - name: Build Example
        run: cmake --build build-example --config Debug
      - name: Test Example
        run: ctest --test-dir build-example -C Debug --verbose
