---
name: Build for macOS-15
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - src/**
      - test/**
      - benchmark/**
      - cmake/**
      - CMakeLists.txt
      - CMakePresets.json
      - .github/workflows/build-macos-15.yml
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - src/**
      - test/**
      - benchmark/**
      - cmake/**
      - CMakeLists.txt
      - CMakePresets.json
      - .github/workflows/build-macos-15.yml

jobs:
  macOS-15:
    runs-on: macos-15
    env:
      CMAKE_GENERATOR: "Ninja Multi-Config"
      CTEST_OUTPUT_ON_FAILURE: 1
      PTRIE_BRANCH: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4.0'
      - name: Install Build Tools
        run: |
          brew update
          brew install cmake ninja gcc google-sparsehash
      - name: Setup Runner Environment
        run: |
          uname -a
          xcrun --show-sdk-version
          CORES=$(sysctl -n hw.ncpu)
          echo "CMAKE_BUILD_PARALLEL_LEVEL=$CORES" >> $GITHUB_ENV
          echo "CTEST_TEST_PARALLEL_LEVEL=$CORES" >> $GITHUB_ENV
          echo "CTEST_TEST_LOAD=$CORES" >> $GITHUB_ENV
          GCC_PREFIX=$(brew --prefix gcc)
          GCC_VERSION=$(brew list --versions gcc | awk '{print $2}' | cut -d. -f1)
          echo "CC=${GCC_PREFIX}/bin/gcc-${GCC_VERSION}" >> $GITHUB_ENV
          echo "CXX=${GCC_PREFIX}/bin/g++-${GCC_VERSION}" >> $GITHUB_ENV
      - uses: actions/checkout@v5
      - name: Configure Multi-Config (without Sanitizers)
        run: cmake --preset multi -DBENCHMARK_PLOTS=OFF
      - name: Build Debug (without Sanitizers)
        run: cmake --build --preset debug
      - name: Test Debug (without Sanitizers)
        run: ctest --preset debug
#      - name: Build Release (without Sanitizers)
#        run: cmake --build --preset release
#      - name: Test Release (without Sanitizers)
#        run: ctest --preset release
      - name: Quick Release
        run: cmake --workflow --preset quick-release
      - name: Quick Release Install to local
        run: cmake --install build-quick --config Release --prefix "$PWD/local"
      - name: Configure Example with local
        run: cmake -S example -B build-example-local -DCMAKE_PREFIX_PATH="$PWD/local"
      - name: Build Example with local
        run: cmake --build build-example-local --config Debug
      - name: Test Example with local
        run: ctest --test-dir build-example-local -C Debug --verbose
      - name: Configure Example
        run: cmake -S example -B build-example -DPTRIE_BRANCH=${PTRIE_BRANCH}
      - name: Build Example
        run: cmake --build build-example --config Debug
      - name: Test Example
        run: ctest --test-dir build-example -C Debug --verbose
